- name: Install Prometheus on EC2
  hosts: all
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install wget and tar
      apt:
        name:
          - wget
          - tar
        state: present

    - name: Download Prometheus package
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.53.1/prometheus-2.53.1.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Move Prometheus binary
      command: mv /opt/prometheus-2.53.1.linux-amd64/prometheus /usr/local/bin/

    - name: Move promtool binary
      command: mv /opt/prometheus-2.53.1.linux-amd64/promtool /usr/local/bin/

    - name: Create Prometheus service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus Service
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/prometheus --config.file=/opt/prometheus-2.53.1.linux-amd64/prometheus.yml --web.listen-address=:9090
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: started

