---
# ================================
# Download Alertmanager
# ================================
- name: Download Alertmanager
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v0.27.0/alertmanager-0.27.0.linux-amd64.tar.gz"
    dest: /tmp/alertmanager.tar.gz

# ================================
# Extract Alertmanager
# ================================
- name: Extract Alertmanager
  unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: /opt/
    remote_src: yes

# ================================
# Create alertmanager user
# ================================
- name: Create Alertmanager system user
  user:
    name: alertmanager
    system: yes
    shell: /sbin/nologin

# ================================
# Create directories
# ================================
- name: Create Alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: '0755'
  loop:
    - /etc/alertmanager
    - /var/lib/alertmanager

# ================================
# Copy Alertmanager binaries
# ================================
- name: Copy Alertmanager binaries
  copy:
    src: "/opt/alertmanager-0.27.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
    remote_src: yes
  loop:
    - alertmanager
    - amtool

# ================================
# Copy alertmanager.yml
# ================================
- name: Place Alertmanager config
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanager
    mode: '0644'

# ================================
# Create systemd service
# ================================
- name: Create Alertmanager systemd service
  copy:
    dest: /etc/systemd/system/alertmanager.service
    mode: "0644"
    content: |
      [Unit]
      Description=Alertmanager Service
      After=network.target

      [Service]
      User=alertmanager
      Group=alertmanager
      Type=simple
      ExecStart=/usr/local/bin/alertmanager \
        --config.file=/etc/alertmanager/alertmanager.yml \
        --storage.path=/var/lib/alertmanager

      [Install]
      WantedBy=multi-user.target

# ================================
# Reload & start service
# ================================
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable & start Alertmanager service
  systemd:
    name: alertmanager
    enabled: yes
    state: started

